name: Publish Docs
on:
  push:
    branches:
      - main  # Triggers when you push to main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-size: '3.x'

      - name: Install MkDocs and Plugins
        run: |
          pip install mkdocs-material mkdocs-autorefs mkdocs-jupyter mkdocs-include-markdown-plugin mkdocstrings[python]
          # Add any plugins you use here, e.g., pip install mkdocs-material

      - name: Build and Deploy to GitHub Pages
        run: mkdocs gh-deploy --force